---
title: "Data 607 Final Project"
author: "Mohamed Hassan-El Serafi and Eddie Xu"
date: "2023-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## Load Packages
```{r}
library(tidyverse)
library(magrittr)

library(hoopR)

# You can install using the pacman package using the following code:
if (!requireNamespace('pacman', quietly = TRUE)){
  install.packages('pacman')
}
pacman::p_load_current_gh("sportsdataverse/hoopR", dependencies = TRUE, update = TRUE)

#remote install if necessary
remotes::install_github("saiemgilani/hoopR")
```

## Regular Season Team Stat
```{r}
# extract team stat starting from 2001
team_stat_data_01 <- nba_leaguedashteamstats(season = "2001-02", season_type = "Regular Season")
team_stat_data_02 <- nba_leaguedashteamstats(season = "2002-03", season_type = "Regular Season")
team_stat_data_03 <- nba_leaguedashteamstats(season = "2003-04", season_type = "Regular Season")
team_stat_data_04 <- nba_leaguedashteamstats(season = "2004-05", season_type = "Regular Season")
team_stat_data_05 <- nba_leaguedashteamstats(season = "2005-06", season_type = "Regular Season")
team_stat_data_06 <- nba_leaguedashteamstats(season = "2006-07", season_type = "Regular Season")
team_stat_data_07 <- nba_leaguedashteamstats(season = "2007-08", season_type = "Regular Season")
team_stat_data_08 <- nba_leaguedashteamstats(season = "2008-09", season_type = "Regular Season")
team_stat_data_09 <- nba_leaguedashteamstats(season = "2009-10", season_type = "Regular Season")
team_stat_data_10 <- nba_leaguedashteamstats(season = "2010-11", season_type = "Regular Season")
team_stat_data_11 <- nba_leaguedashteamstats(season = "2011-12", season_type = "Regular Season")
team_stat_data_12 <- nba_leaguedashteamstats(season = "2012-13", season_type = "Regular Season")
team_stat_data_13 <- nba_leaguedashteamstats(season = "2013-14", season_type = "Regular Season")
team_stat_data_14 <- nba_leaguedashteamstats(season = "2014-15", season_type = "Regular Season")
team_stat_data_15 <- nba_leaguedashteamstats(season = "2015-16", season_type = "Regular Season")
team_stat_data_16 <- nba_leaguedashteamstats(season = "2016-17", season_type = "Regular Season")
team_stat_data_17 <- nba_leaguedashteamstats(season = "2017-18", season_type = "Regular Season")
team_stat_data_18 <- nba_leaguedashteamstats(season = "2018-19", season_type = "Regular Season")
team_stat_data_19 <- nba_leaguedashteamstats(season = "2019-20", season_type = "Regular Season")
team_stat_data_20 <- nba_leaguedashteamstats(season = "2020-21", season_type = "Regular Season")
team_stat_data_21 <- nba_leaguedashteamstats(season = "2021-22", season_type = "Regular Season")
```

```{r}
#convert all extracted data into data frames and add a new column
team_stat_data_01 <- team_stat_data_01 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2001-02", season_year = "2002")

team_stat_data_02 <- team_stat_data_02 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2002-03", season_year = "2003")

team_stat_data_03<- team_stat_data_03 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2003-04", season_year = "2004")

team_stat_data_04 <- team_stat_data_04 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2004-05", season_year = "2005")

team_stat_data_05 <- team_stat_data_05 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2005-06", season_year = "2006")

team_stat_data_06 <- team_stat_data_06 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2006-07", season_year = "2007")

team_stat_data_07 <- team_stat_data_07 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2007-08", season_year = "2008")

team_stat_data_08 <- team_stat_data_08 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2008-09", season_year = "2009")

team_stat_data_09 <- team_stat_data_09 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2009-10", season_year = "2010")

team_stat_data_10 <- team_stat_data_10 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2010-11", season_year = "2011")

team_stat_data_11 <- team_stat_data_11 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2011-12", season_year = "2012")

team_stat_data_12 <- team_stat_data_12 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2012-13", season_year = "2013")

team_stat_data_13 <- team_stat_data_13 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2013-14", season_year = "2014")

team_stat_data_14 <- team_stat_data_14 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2014-15", season_year = "2015")

team_stat_data_15 <- team_stat_data_15 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2015-16", season_year = "2016")

team_stat_data_16 <- team_stat_data_16 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2016-17", season_year = "2017")

team_stat_data_17 <- team_stat_data_17 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2017-18", season_year = "2018")

team_stat_data_18 <- team_stat_data_18 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2018-19", season_year = "2019")

team_stat_data_19 <- team_stat_data_19 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2019-20", season_year = "2020")

team_stat_data_20 <- team_stat_data_20 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2020-21", season_year = "2021")

team_stat_data_21 <- team_stat_data_21 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamStats.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2021-22", season_year= "2022")

#merge all seasons into one data frame
nba_historical_teamstat_list <- list(team_stat_data_01, team_stat_data_02, team_stat_data_03, team_stat_data_04, team_stat_data_05, team_stat_data_06, team_stat_data_07, team_stat_data_08, team_stat_data_09, team_stat_data_10, team_stat_data_11, team_stat_data_12, team_stat_data_13, team_stat_data_14, team_stat_data_15, team_stat_data_16, team_stat_data_17, team_stat_data_18, team_stat_data_19, team_stat_data_20, team_stat_data_21)

nba_historical_team_data <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), nba_historical_teamstat_list)

DT::datatable(nba_historical_team_data)
```

## Regular Season for Clutch Performance Per Teams
```{r}
# extract clutch stat from regular season starting from 2001
tc_data_01 <- nba_leaguedashteamclutch(season = "2001-02", season_type = "Regular Season")
tc_data_02 <- nba_leaguedashteamclutch(season = "2002-03", season_type = "Regular Season")
tc_data_03 <- nba_leaguedashteamclutch(season = "2003-04", season_type = "Regular Season")
tc_data_04 <- nba_leaguedashteamclutch(season = "2004-05", season_type = "Regular Season")
tc_data_05 <- nba_leaguedashteamclutch(season = "2005-06", season_type = "Regular Season")
tc_data_06 <- nba_leaguedashteamclutch(season = "2006-07", season_type = "Regular Season")
tc_data_07 <- nba_leaguedashteamclutch(season = "2007-08", season_type = "Regular Season")
tc_data_08 <- nba_leaguedashteamclutch(season = "2008-09", season_type = "Regular Season")
tc_data_09 <- nba_leaguedashteamclutch(season = "2009-10", season_type = "Regular Season")
tc_data_10 <- nba_leaguedashteamclutch(season = "2010-11", season_type = "Regular Season")
tc_data_11 <- nba_leaguedashteamclutch(season = "2011-12", season_type = "Regular Season")
tc_data_12 <- nba_leaguedashteamclutch(season = "2012-13", season_type = "Regular Season")
tc_data_13 <- nba_leaguedashteamclutch(season = "2013-14", season_type = "Regular Season")
tc_data_14 <- nba_leaguedashteamclutch(season = "2014-15", season_type = "Regular Season")
tc_data_15 <- nba_leaguedashteamclutch(season = "2015-16", season_type = "Regular Season")
tc_data_16 <- nba_leaguedashteamclutch(season = "2016-17", season_type = "Regular Season")
tc_data_17 <- nba_leaguedashteamclutch(season = "2017-18", season_type = "Regular Season")
tc_data_18 <- nba_leaguedashteamclutch(season = "2018-19", season_type = "Regular Season")
tc_data_19 <- nba_leaguedashteamclutch(season = "2019-20", season_type = "Regular Season")
tc_data_20 <- nba_leaguedashteamclutch(season = "2020-21", season_type = "Regular Season")
tc_data_21 <- nba_leaguedashteamclutch(season = "2021-22", season_type = "Regular Season")
```

```{r}
#convert all extracted data into data frames and add a new column
tc_data_01 <- tc_data_01 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2001-02", season_year = "2002")

tc_data_02 <- tc_data_02 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2002-03", season_year = "2003")

tc_data_03 <- tc_data_03 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2003-04", season_year = "2004")

tc_data_04 <- tc_data_04 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2004-05", season_year = "2005")

tc_data_05 <- tc_data_05 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2005-06", season_year = "2006")

tc_data_06 <- tc_data_06 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2006-07", season_year = "2007")

tc_data_07 <- tc_data_07 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2007-08", season_year = "2008")

tc_data_08 <- tc_data_08 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2008-09", season_year = "2009")

tc_data_09 <- tc_data_09 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2009-10", season_year = "2010")

tc_data_10 <- tc_data_10 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2010-11", season_year = "2011")

tc_data_11 <- tc_data_11 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2011-12", season_year = "2012")

tc_data_12 <- tc_data_12 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2012-13", season_year = "2013")

tc_data_13 <- tc_data_13 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2013-14", season_year = "2014")

tc_data_14 <- tc_data_14 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2014-15", season_year = "2015")

tc_data_15 <- tc_data_15 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2015-16", season_year = "2016")

tc_data_16 <- tc_data_16 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2016-17", season_year = "2017")

tc_data_17 <- tc_data_17 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2017-18", season_year = "2018")

tc_data_18 <- tc_data_18 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2018-19", season_year = "2019")

tc_data_19 <- tc_data_19 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2019-20", season_year = "2020")

tc_data_20 <- tc_data_20 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2020-21", season_year = "2021")

tc_data_21 <- tc_data_21 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2021-22", season_year = "2022")

#merge all data
nba_historical_clutch_list <- list(tc_data_01, tc_data_02, tc_data_03, tc_data_04, tc_data_05, tc_data_06, tc_data_07, tc_data_08, tc_data_09, tc_data_10, tc_data_11, tc_data_12, tc_data_13, tc_data_14, tc_data_15, tc_data_16, tc_data_17, tc_data_18, tc_data_19, tc_data_20, tc_data_21)

nba_historical_clutch_data <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), nba_historical_clutch_list)
nba_historical_clutch_data$Season_Type <- "Regular Season"

DT::datatable(nba_historical_clutch_data)
```

## Regular Season for Clutch Performance Per Players
```{r}
# extract all player clutch starting 2011
tc_playerdata_11 <- nba_leaguedashplayerclutch(season = "2011-12", season_type = "Regular Season")
tc_playerdata_12 <- nba_leaguedashplayerclutch(season = "2012-13", season_type = "Regular Season")
tc_playerdata_13 <- nba_leaguedashplayerclutch(season = "2013-14", season_type = "Regular Season")
tc_playerdata_14 <- nba_leaguedashplayerclutch(season = "2014-15", season_type = "Regular Season")
tc_playerdata_15 <- nba_leaguedashplayerclutch(season = "2015-16", season_type = "Regular Season")
tc_playerdata_16 <- nba_leaguedashplayerclutch(season = "2016-17", season_type = "Regular Season")
tc_playerdata_17 <- nba_leaguedashplayerclutch(season = "2017-18", season_type = "Regular Season")
tc_playerdata_18 <- nba_leaguedashplayerclutch(season = "2018-19", season_type = "Regular Season")
tc_playerdata_19 <- nba_leaguedashplayerclutch(season = "2019-20", season_type = "Regular Season")
tc_playerdata_20 <- nba_leaguedashplayerclutch(season = "2020-21", season_type = "Regular Season")
tc_playerdata_21 <- nba_leaguedashplayerclutch(season = "2021-22", season_type = "Regular Season")
```

```{r}
# convert all extracted data into data frames and add a new column of player season
tc_playerdata_11 <- tc_playerdata_11 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2011-12")

tc_playerdata_12 <- tc_playerdata_12 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2012-13")

tc_playerdata_13 <- tc_playerdata_13 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2013-14")

tc_playerdata_14 <- tc_playerdata_14 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2014-15")

tc_playerdata_15 <- tc_playerdata_15 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2015-16")

tc_playerdata_16 <- tc_playerdata_16 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2016-17")

tc_playerdata_17 <- tc_playerdata_17 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2017-18")

tc_playerdata_18 <- tc_playerdata_18 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2018-19")

tc_playerdata_19 <- tc_playerdata_19 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2019-20")

tc_playerdata_20 <- tc_playerdata_20 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2020-21")

tc_playerdata_21 <- tc_playerdata_21 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2021-22")

# merge all data
nba_historical_player_clutch_list <- list(tc_playerdata_11, tc_playerdata_12, tc_playerdata_13, tc_playerdata_14, tc_playerdata_15, tc_playerdata_16, tc_playerdata_17, tc_playerdata_18, tc_playerdata_19, tc_playerdata_20, tc_playerdata_21)

nba_historical_player_clutch_data <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), nba_historical_player_clutch_list)

nba_historical_player_clutch_data$Season_Type <- "Regular Season"

DT::datatable(nba_historical_player_clutch_data)
```

## Team Clutch Playoffs 2001-02 to 2021-22
```{r}
team_clutch_playoffs02 <- nba_leaguedashteamclutch(season = "2001-02", season_type = "Playoffs")
team_clutch_playoffs02 <- team_clutch_playoffs02 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2001-02", season_year = "2002")

team_clutch_playoffs03 <- nba_leaguedashteamclutch(season = "2002-03", season_type = "Playoffs")
team_clutch_playoffs03 <- team_clutch_playoffs03 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2002-03", season_year = "2003")

team_clutch_playoffs04 <- nba_leaguedashteamclutch(season = "2003-04", season_type = "Playoffs")
team_clutch_playoffs04 <- team_clutch_playoffs04 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2003-04", season_year = "2004")

team_clutch_playoffs05 <- nba_leaguedashteamclutch(season = "2004-05", season_type = "Playoffs")
team_clutch_playoffs05 <- team_clutch_playoffs05 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2004-05", season_year = "2005")

team_clutch_playoffs06 <- nba_leaguedashteamclutch(season = "2005-06", season_type = "Playoffs")
team_clutch_playoffs06 <- team_clutch_playoffs06 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2005-06", season_year = "2006")

team_clutch_playoffs07 <- nba_leaguedashteamclutch(season = "2006-07", season_type = "Playoffs")
team_clutch_playoffs07 <- team_clutch_playoffs07 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2006-07", season_year = "2007")

team_clutch_playoffs08 <- nba_leaguedashteamclutch(season = "2007-08", season_type = "Playoffs")
team_clutch_playoffs08 <- team_clutch_playoffs08 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2007-08", season_year = "2008")

team_clutch_playoffs09 <- nba_leaguedashteamclutch(season = "2008-09", season_type = "Playoffs")
team_clutch_playoffs09 <- team_clutch_playoffs09 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2008-09", season_year = "2009")

team_clutch_playoffs10 <- nba_leaguedashteamclutch(season = "2009-10", season_type = "Playoffs")
team_clutch_playoffs10 <- team_clutch_playoffs10 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2009-10", season_year = "2010")

team_clutch_playoffs11 <- nba_leaguedashteamclutch(season = "2010-11", season_type = "Playoffs")
team_clutch_playoffs11 <- team_clutch_playoffs11 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2010-11", season_year = "2011")

team_clutch_playoffs12 <- nba_leaguedashteamclutch(season = "2011-12", season_type = "Playoffs")
team_clutch_playoffs12 <- team_clutch_playoffs12 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2011-12", season_year = "2012")

team_clutch_playoffs13 <- nba_leaguedashteamclutch(season = "2012-13", season_type = "Playoffs")
team_clutch_playoffs13 <- team_clutch_playoffs13 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2012-13", season_year = "2013")

team_clutch_playoffs14 <- nba_leaguedashteamclutch(season = "2013-14", season_type = "Playoffs")
team_clutch_playoffs14 <- team_clutch_playoffs14 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2013-14", season_year = "2014")

team_clutch_playoffs15 <- nba_leaguedashteamclutch(season = "2014-15", season_type = "Playoffs")
team_clutch_playoffs15 <- team_clutch_playoffs15 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2014-15", season_year = "2015")

team_clutch_playoffs16 <- nba_leaguedashteamclutch(season = "2015-16", season_type = "Playoffs")
team_clutch_playoffs16 <- team_clutch_playoffs16 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2015-16", season_year = "2016")

team_clutch_playoffs17 <- nba_leaguedashteamclutch(season = "2016-17", season_type = "Playoffs")
team_clutch_playoffs17 <- team_clutch_playoffs17 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2016-17", season_year = "2017")

team_clutch_playoffs18 <- nba_leaguedashteamclutch(season = "2017-18", season_type = "Playoffs")
team_clutch_playoffs18 <- team_clutch_playoffs18 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2017-18", season_year = "2018")

team_clutch_playoffs19 <- nba_leaguedashteamclutch(season = "2018-19", season_type = "Playoffs")
team_clutch_playoffs19 <- team_clutch_playoffs19 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2018-19", season_year = "2019")

team_clutch_playoffs20 <- nba_leaguedashteamclutch(season = "2019-20", season_type = "Playoffs")
team_clutch_playoffs20 <- team_clutch_playoffs20 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2019-20", season_year = "2020")

team_clutch_playoffs21 <- nba_leaguedashteamclutch(season = "2020-21", season_type = "Playoffs")
team_clutch_playoffs21 <- team_clutch_playoffs21 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2020-21", season_year = "2021")

team_clutch_playoffs22 <- nba_leaguedashteamclutch(season = "2021-22", season_type = "Playoffs")
team_clutch_playoffs22 <- team_clutch_playoffs22 %>%
  data.frame(check.names = FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2021-22", season_year = "2022")
```

```{r}
# merge all data frames into one
team_df_list = list(team_clutch_playoffs02, team_clutch_playoffs03, 
               team_clutch_playoffs04, team_clutch_playoffs05,
               team_clutch_playoffs06, team_clutch_playoffs07,
               team_clutch_playoffs08, team_clutch_playoffs09, 
               team_clutch_playoffs10, team_clutch_playoffs11,
               team_clutch_playoffs12, team_clutch_playoffs13,
               team_clutch_playoffs14, team_clutch_playoffs15,
               team_clutch_playoffs16, team_clutch_playoffs17,
               team_clutch_playoffs18, team_clutch_playoffs19, 
               team_clutch_playoffs20, team_clutch_playoffs21,
               team_clutch_playoffs22)

team_new_df_list <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), team_df_list)
team_new_df_list$Season_Type <- "Playoffs"

DT::datatable(team_new_df_list)
```

## Player Clutch 2011-12 to 2021-22
```{r}
# extract player data starting from season 2011 to 2021
player_clutch_playoffs12 <- nba_leaguedashplayerclutch(season = "2011-12", season_type = "Playoffs")
player_clutch_playoffs13 <- nba_leaguedashplayerclutch(season = "2012-13", season_type = "Playoffs")
player_clutch_playoffs14 <- nba_leaguedashplayerclutch(season = "2013-14", season_type = "Playoffs")
player_clutch_playoffs15 <- nba_leaguedashplayerclutch(season = "2014-15", season_type = "Playoffs")
player_clutch_playoffs16 <- nba_leaguedashplayerclutch(season = "2015-16", season_type = "Playoffs")
player_clutch_playoffs17 <- nba_leaguedashplayerclutch(season = "2016-17", season_type = "Playoffs")
player_clutch_playoffs18 <- nba_leaguedashplayerclutch(season = "2017-18", season_type = "Playoffs")
player_clutch_playoffs19 <- nba_leaguedashplayerclutch(season = "2018-19", season_type = "Playoffs")
player_clutch_playoffs20 <- nba_leaguedashplayerclutch(season = "2019-20", season_type = "Playoffs")
player_clutch_playoffs21 <- nba_leaguedashplayerclutch(season = "2020-21", season_type = "Playoffs")
player_clutch_playoffs22 <- nba_leaguedashplayerclutch(season = "2021-22", season_type = "Playoffs")
```

```{r}
# convert all extracted data into data frames and add a new column
player_clutch_playoffs12 <- nba_leaguedashplayerclutch(season = "2011-12", season_type = "Playoffs")
player_clutch_playoffs12 <- data.frame(player_clutch_playoffs12, check.names = FALSE)
player_clutch_playoffs12 <- player_clutch_playoffs12 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs12$player_season <- "2011-12"

player_clutch_playoffs13 <- nba_leaguedashplayerclutch(season = "2012-13", season_type = "Playoffs")
player_clutch_playoffs13 <- data.frame(player_clutch_playoffs13, check.names = FALSE)
player_clutch_playoffs13 <- player_clutch_playoffs13 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs13$player_season <- "2012-13"

player_clutch_playoffs14 <- nba_leaguedashplayerclutch(season = "2013-14", season_type = "Playoffs")
player_clutch_playoffs14 <- data.frame(player_clutch_playoffs14, check.names = FALSE)
player_clutch_playoffs14 <- player_clutch_playoffs14 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs14$player_season <- "2013-14"

player_clutch_playoffs15 <- nba_leaguedashplayerclutch(season = "2014-15", season_type = "Playoffs")
player_clutch_playoffs15 <- data.frame(player_clutch_playoffs15, check.names = FALSE)
player_clutch_playoffs15 <- player_clutch_playoffs15 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs15$player_season <- "2014-15"

player_clutch_playoffs16 <- nba_leaguedashplayerclutch(season = "2015-16", season_type = "Playoffs")
player_clutch_playoffs16 <- data.frame(player_clutch_playoffs16, check.names = FALSE)
player_clutch_playoffs16 <- player_clutch_playoffs16 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs16$player_season <- "2015-16"

player_clutch_playoffs17 <- nba_leaguedashplayerclutch(season = "2016-17", season_type = "Playoffs")
player_clutch_playoffs17 <- data.frame(player_clutch_playoffs17, check.names = FALSE)
player_clutch_playoffs17 <- player_clutch_playoffs17 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs17$player_season <- "2016-17"

player_clutch_playoffs18 <- nba_leaguedashplayerclutch(season = "2017-18", season_type = "Playoffs")
player_clutch_playoffs18 <- data.frame(player_clutch_playoffs18, check.names = FALSE)
player_clutch_playoffs18 <- player_clutch_playoffs18 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs18$player_season <- "2017-18"

player_clutch_playoffs19 <- nba_leaguedashplayerclutch(season = "2018-19", season_type = "Playoffs")
player_clutch_playoffs19 <- data.frame(player_clutch_playoffs19, check.names = FALSE)
player_clutch_playoffs19 <- player_clutch_playoffs19 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs19$player_season <- "2018-19"

player_clutch_playoffs20 <- nba_leaguedashplayerclutch(season = "2019-20", season_type = "Playoffs")
player_clutch_playoffs20 <- data.frame(player_clutch_playoffs20, check.names = FALSE)
player_clutch_playoffs20 <- player_clutch_playoffs12 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs20$player_season <- "2019-20"

player_clutch_playoffs21 <- nba_leaguedashplayerclutch(season = "2020-21", season_type = "Playoffs")
player_clutch_playoffs21 <- data.frame(player_clutch_playoffs21, check.names = FALSE)
player_clutch_playoffs21 <- player_clutch_playoffs21 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs21$player_season <- "2020-21"

player_clutch_playoffs22 <- nba_leaguedashplayerclutch(season = "2021-22", season_type = "Playoffs")
player_clutch_playoffs22 <- data.frame(player_clutch_playoffs22, check.names = FALSE)
player_clutch_playoffs22 <- player_clutch_playoffs22 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs22$player_season <- "2021-22"

# merge all data
df_list = list(player_clutch_playoffs12, player_clutch_playoffs13, 
               player_clutch_playoffs14, player_clutch_playoffs15,
               player_clutch_playoffs16, player_clutch_playoffs17,
               player_clutch_playoffs18, player_clutch_playoffs19, 
               player_clutch_playoffs20, player_clutch_playoffs21, player_clutch_playoffs22)

player_new_df_list <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), df_list)

player_new_df_list$Season_Type <- "Playoffs"

DT::datatable(player_new_df_list)
```

### Write CSV Files
```{r}
# merge all regular season and playoffs clutch data
nba_all_teamclutch_data <- rbind(team_new_df_list, nba_historical_clutch_data)
nba_all_playerclutch_data <- rbind(player_new_df_list, nba_historical_player_clutch_data)


path_csv <- getwd()
path_csv2 <- getwd()
path_csv3 <- getwd()
write.csv(nba_all_teamclutch_data, file.path(path_csv, "Team_Clutch_Data.csv"))
write.csv(nba_all_playerclutch_data, file.path(path_csv2, "Player_Clutch_Data.csv"))
write.csv(nba_historical_team_data, file.path(path_csv3, "Team_Stat_Regular_Season_Datat.csv"))
```


