---
title: "Data 607 Final Project Data Extraction"
author: "Mohamed Hassan-El Serafi and Eddie Xu"
date: "2023-05-14"
output: html_document
---

 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```



```{r}
library(tidyverse)
library(nbastatR)
library(hoopR)
```




```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
```





## Team Clutch Regular Season 2001-02 to 2021-22

```{r}
# extract clutch stat from regular season starting from 2001
tc_data_01 <- nba_leaguedashteamclutch(season = "2001-02", season_type = "Regular Season")
tc_data_02 <- nba_leaguedashteamclutch(season = "2002-03", season_type = "Regular Season")
tc_data_03 <- nba_leaguedashteamclutch(season = "2003-04", season_type = "Regular Season")
tc_data_04 <- nba_leaguedashteamclutch(season = "2004-05", season_type = "Regular Season")
tc_data_05 <- nba_leaguedashteamclutch(season = "2005-06", season_type = "Regular Season")
tc_data_06 <- nba_leaguedashteamclutch(season = "2006-07", season_type = "Regular Season")
tc_data_07 <- nba_leaguedashteamclutch(season = "2007-08", season_type = "Regular Season")
tc_data_08 <- nba_leaguedashteamclutch(season = "2008-09", season_type = "Regular Season")
tc_data_09 <- nba_leaguedashteamclutch(season = "2009-10", season_type = "Regular Season")
tc_data_10 <- nba_leaguedashteamclutch(season = "2010-11", season_type = "Regular Season")
tc_data_11 <- nba_leaguedashteamclutch(season = "2011-12", season_type = "Regular Season")
tc_data_12 <- nba_leaguedashteamclutch(season = "2012-13", season_type = "Regular Season")
tc_data_13 <- nba_leaguedashteamclutch(season = "2013-14", season_type = "Regular Season")
tc_data_14 <- nba_leaguedashteamclutch(season = "2014-15", season_type = "Regular Season")
tc_data_15 <- nba_leaguedashteamclutch(season = "2015-16", season_type = "Regular Season")
tc_data_16 <- nba_leaguedashteamclutch(season = "2016-17", season_type = "Regular Season")
tc_data_17 <- nba_leaguedashteamclutch(season = "2017-18", season_type = "Regular Season")
tc_data_18 <- nba_leaguedashteamclutch(season = "2018-19", season_type = "Regular Season")
tc_data_19 <- nba_leaguedashteamclutch(season = "2019-20", season_type = "Regular Season")
tc_data_20 <- nba_leaguedashteamclutch(season = "2020-21", season_type = "Regular Season")
tc_data_21 <- nba_leaguedashteamclutch(season = "2021-22", season_type = "Regular Season")
```




```{r}
#convert all extracted data into data frames and add a new column
tc_data_01 <- tc_data_01 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2001-02")


tc_data_02 <- tc_data_02 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2002-03")


tc_data_03 <- tc_data_03 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2003-04")


tc_data_04 <- tc_data_04 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2004-05")



tc_data_05 <- tc_data_05 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2005-06")




tc_data_06 <- tc_data_06 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2006-07")



tc_data_07 <- tc_data_07 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2007-08")




tc_data_08 <- tc_data_08 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2008-09")



tc_data_09 <- tc_data_09 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2009-10")

tc_data_10 <- tc_data_10 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2010-11")

tc_data_11 <- tc_data_11 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2011-12")

tc_data_12 <- tc_data_12 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2012-13")

tc_data_13 <- tc_data_13 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2013-14")

tc_data_14 <- tc_data_14 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2014-15")

tc_data_15 <- tc_data_15 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2015-16")

tc_data_16 <- tc_data_16 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2016-17")

tc_data_17 <- tc_data_17 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2017-18")

tc_data_18 <- tc_data_18 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2018-19")

tc_data_19 <- tc_data_19 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2019-20")

tc_data_20 <- tc_data_20 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2020-21")

tc_data_21 <- tc_data_21 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE)) %>%
  add_column(team_season = "2021-22")





nba_historical_clutch_list <- list(tc_data_01, tc_data_02, tc_data_03, tc_data_04, tc_data_05, tc_data_06, tc_data_07, tc_data_08, tc_data_09, tc_data_10, tc_data_11, tc_data_12, tc_data_13, tc_data_14, tc_data_15, tc_data_16, tc_data_17, tc_data_18, tc_data_19, tc_data_20)



#merge all data
#nba_historical_clutch_list <- list(tc_data_2000_01, tc_data_2001_02, tc_data_2002_03, tc_data_2003_04, tc_data_2004_05, tc_data_2005_06, tc_data_2006_07, tc_data_2007_08, tc_data_2008_09, tc_data_2009_10, tc_data_2010_11, tc_data_2011_12, tc_data_2012_13, tc_data_2013_14, tc_data_2014_15, tc_data_2015_16, tc_data_2016_17, tc_data_2017_18, tc_data_2018_19, tc_data_2019_20, tc_data_2020_21)

nba_historical_clutch_data <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), nba_historical_clutch_list)
nba_historical_clutch_data$Season_Type <- "Regular Season"
DT::datatable(nba_historical_clutch_data)
```






## Team Clutch Playoffs 2001-02 to 2021-22



```{r}
team_clutch_playoffs02 <- nba_leaguedashteamclutch(season = "2001-02", season_type = "Playoffs")
team_clutch_playoffs02 <- data.frame(team_clutch_playoffs02, check.names = FALSE)
team_clutch_playoffs02 <- team_clutch_playoffs02 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs02$team_season <- "2001-02"
```


```{r}
team_clutch_playoffs03 <- nba_leaguedashteamclutch(season = "2002-03", season_type = "Playoffs")
team_clutch_playoffs03 <- data.frame(team_clutch_playoffs03, check.names = FALSE)
team_clutch_playoffs03 <- team_clutch_playoffs03 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs03$team_season <- "2002-03"
```



```{r}
team_clutch_playoffs04 <- nba_leaguedashteamclutch(season = "2003-04", season_type = "Playoffs")
team_clutch_playoffs04 <- data.frame(team_clutch_playoffs04, check.names = FALSE)
team_clutch_playoffs04 <- team_clutch_playoffs04 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs04$team_season <- "2003-04"
```



```{r}
team_clutch_playoffs05 <- nba_leaguedashteamclutch(season = "2004-05", season_type = "Playoffs")
team_clutch_playoffs05 <- data.frame(team_clutch_playoffs05, check.names = FALSE)
team_clutch_playoffs05 <- team_clutch_playoffs05 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs05$team_season <- "2004-05"
```


```{r}
team_clutch_playoffs06 <- nba_leaguedashteamclutch(season = "2005-06", season_type = "Playoffs")
team_clutch_playoffs06 <- data.frame(team_clutch_playoffs06)
team_clutch_playoffs06 <- team_clutch_playoffs06 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs06$team_season <- "2005-06"
```


```{r}
team_clutch_playoffs07 <- nba_leaguedashteamclutch(season = "2006-07", season_type = "Playoffs")
team_clutch_playoffs07 <- data.frame(team_clutch_playoffs07, check.names = FALSE)
team_clutch_playoffs07 <- team_clutch_playoffs07 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs07$team_season <- "2006-07"
```



```{r}
team_clutch_playoffs08 <- nba_leaguedashteamclutch(season = "2007-08", season_type = "Playoffs")
team_clutch_playoffs08 <- data.frame(team_clutch_playoffs08, check.names = FALSE)
team_clutch_playoffs08 <- team_clutch_playoffs08 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs08$team_season <- "2007-08"
```


```{r}
team_clutch_playoffs09 <- nba_leaguedashteamclutch(season = "2008-09", season_type = "Playoffs")
team_clutch_playoffs09 <- data.frame(team_clutch_playoffs09, check.names = FALSE)
team_clutch_playoffs09 <- team_clutch_playoffs09 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs09$team_season <- "2008-09"
```


```{r}
team_clutch_playoffs10 <- nba_leaguedashteamclutch(season = "2009-10", season_type = "Playoffs")
team_clutch_playoffs10 <- data.frame(team_clutch_playoffs10, check.names = FALSE)
team_clutch_playoffs10 <- team_clutch_playoffs10 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs10$team_season <- "2009-10"
```


```{r}
team_clutch_playoffs11 <- nba_leaguedashteamclutch(season = "2010-11", season_type = "Playoffs")
team_clutch_playoffs11 <- data.frame(team_clutch_playoffs11, check.names = FALSE)
team_clutch_playoffs11 <- team_clutch_playoffs11 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs11$team_season <- "2010-11"
```

```{r}
team_clutch_playoffs12 <- nba_leaguedashteamclutch(season = "2011-12", season_type = "Playoffs")
team_clutch_playoffs12 <- data.frame(team_clutch_playoffs12, check.names = FALSE)
team_clutch_playoffs12 <- team_clutch_playoffs12 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs12$team_season <- "2011-12"
```


```{r}
team_clutch_playoffs13 <- nba_leaguedashteamclutch(season = "2012-13", season_type = "Playoffs")
team_clutch_playoffs13 <- data.frame(team_clutch_playoffs13, check.names = FALSE)
team_clutch_playoffs13 <- team_clutch_playoffs13 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs13$team_season <- "2012-13"
```


```{r}
team_clutch_playoffs14 <- nba_leaguedashteamclutch(season = "2013-14", season_type = "Playoffs")
team_clutch_playoffs14 <- data.frame(team_clutch_playoffs14, check.names = FALSE)
team_clutch_playoffs14 <- team_clutch_playoffs14 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs14$team_season <- "2013-14"
```



```{r}
team_clutch_playoffs15 <- nba_leaguedashteamclutch(season = "2014-15", season_type = "Playoffs")
team_clutch_playoffs15 <- data.frame(team_clutch_playoffs15, check.names = FALSE)
team_clutch_playoffs15 <- team_clutch_playoffs15 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs15$team_season <- "2014-15"
```


```{r}
team_clutch_playoffs16 <- nba_leaguedashteamclutch(season = "2015-16", season_type = "Playoffs")
team_clutch_playoffs16 <- data.frame(team_clutch_playoffs16, check.names = FALSE)
team_clutch_playoffs16 <- team_clutch_playoffs16 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs16$team_season <- "2015-16"
```



```{r}
team_clutch_playoffs17 <- nba_leaguedashteamclutch(season = "2016-17", season_type = "Playoffs")
team_clutch_playoffs17 <- data.frame(team_clutch_playoffs17, check.names = FALSE)
team_clutch_playoffs17 <- team_clutch_playoffs17 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs17$team_season<- "2016-17"
```


```{r}
team_clutch_playoffs18 <- nba_leaguedashteamclutch(season = "2017-18", season_type = "Playoffs")
team_clutch_playoffs18 <- data.frame(team_clutch_playoffs18, check.names = FALSE)
team_clutch_playoffs18 <- team_clutch_playoffs18 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs18$team_season <- "2017-18"
```

```{r}
team_clutch_playoffs19 <- nba_leaguedashteamclutch(season = "2018-19", season_type = "Playoffs")
team_clutch_playoffs19 <- data.frame(team_clutch_playoffs19, check.names = FALSE)
team_clutch_playoffs19 <- team_clutch_playoffs19 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs19$team_season <- "2018-19"
```


```{r}
team_clutch_playoffs20 <- nba_leaguedashteamclutch(season = "2019-20", season_type = "Playoffs")
team_clutch_playoffs20 <- data.frame(team_clutch_playoffs20, check.names = FALSE)
team_clutch_playoffs20 <- team_clutch_playoffs20 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs20$team_season <- "2019-20"
```



```{r}
team_clutch_playoffs21 <- nba_leaguedashteamclutch(season = "2020-21", season_type = "Playoffs")
team_clutch_playoffs21 <- data.frame(team_clutch_playoffs21, check.names = FALSE)
team_clutch_playoffs21 <- team_clutch_playoffs21 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs21$team_season <- "2020-21"
```

```{r}
team_clutch_playoffs22 <- nba_leaguedashteamclutch(season = "2021-22", season_type = "Playoffs")
team_clutch_playoffs22 <- data.frame(team_clutch_playoffs22, check.names = FALSE)
team_clutch_playoffs22 <- team_clutch_playoffs22 %>%
  rename_with(~ gsub("LeagueDashTeamClutch.", "",.x, fixed=TRUE))
team_clutch_playoffs22$team_season <- "2021-22"
```




```{r}
team_df_list = list(team_clutch_playoffs02, team_clutch_playoffs03, 
               team_clutch_playoffs04, team_clutch_playoffs05,
               team_clutch_playoffs06, team_clutch_playoffs07,
               team_clutch_playoffs08, team_clutch_playoffs09, 
               team_clutch_playoffs10, team_clutch_playoffs11,
               team_clutch_playoffs12, team_clutch_playoffs13,
               team_clutch_playoffs14, team_clutch_playoffs15,
               team_clutch_playoffs16, team_clutch_playoffs17,
               team_clutch_playoffs18, team_clutch_playoffs19, 
               team_clutch_playoffs20, team_clutch_playoffs21,
               team_clutch_playoffs22)



team_new_df_list <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), team_df_list)
team_new_df_list$Season_Type <- "Playoffs"
DT::datatable(team_new_df_list)
```




## Merge Regular Season and Playoffs



```{r}
team_new_df_list2 <- rbind(team_new_df_list, nba_historical_clutch_data)
DT::datatable(team_new_df_list2)
```


```{r}
path_csv <- getwd()
```


```{r}
write.csv(team_new_df_list2, file.path(path_csv, "Team_Clutch_Data.csv"))
```



```{r}
new_team_csv <- read.csv("https://raw.githubusercontent.com/moham6839/Data607_Final_Project/master/Team_Clutch_Data.csv")
head(new_team_csv)
```



## Calculating Team Offensive Efficiency

```{r}
#Basic Possession Formula=0.96*[(new_tea)+(Turnovers)+0.44*(Free Throw Attempts)-(Offensive Rebounds)]
```




```{r}
BPF <- 0.96*(new_team_csv$FGA)+(new_team_csv$TOV) + 0.44*(new_team_csv$FTA)-new_team_csv$OREB
```


```{r}
new_team_csv <- new_team_csv %>%
  mutate(team_possession = 0.96*(new_team_csv$FGA)+(new_team_csv$TOV) + 0.44*(new_team_csv$FTA)-new_team_csv$OREB) %>%
  mutate(team_off = 100*(new_team_csv$PTS/new_team_csv$team_possession))

head(new_team_csv)
```


```{r}
# split the dataset into regular season and playoff seasons
regular_season_dataset <- new_team_csv %>%
  filter(Season_Type == "Regular Season")

playoff_season_dataset <- new_team_csv %>%
  filter(Season_Type == "Playoffs")
```


```{r}
regular_season_dataset %>% 
  ggplot(aes(x=`W`)) +
  geom_histogram(bins = 10) +
  labs(title="Amount of WinShares for Each Player",
       x="Number of WinShares",
       y="Count")
```


```{r}
playoff_season_dataset %>% 
  ggplot(aes(x=`W`)) +
  geom_histogram(bins = 10) +
  labs(title="Amount of Win for Each Player",
       x="Number of Wins",
       y="Count")
```


```{r}
new_df <- regular_season_dataset %>%
  select(W, PLUS_MINUS, PTS, AST, FGM, FG3M, FTM, REB, TOV, team_possession, team_off)
```


```{r}
cor(new_df)
```




```{r}
rs_team_lm2 <- lm(W ~ PLUS_MINUS + FGM + FTM + FG3M + TOV + REB + AST, 
                  data=new_df)
```


```{r}
summary(rs_team_lm2)
```


```{r}
ggplot(rs_team_lm2, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title="Residual vs. Fitted Values Plot") +
  xlab("Fitted values") +
  ylab("Residuals")
```


```{r}
ggplot(data = rs_team_lm2, aes(x = .resid)) +
  geom_histogram(binwidth = 0.4) +
  xlab("Residuals")
```



```{r}
ggplot(data = rs_team_lm2, aes(sample = .resid)) +
  stat_qq()
```

```{r}
library(ggfortify)
autoplot(rs_team_lm2)
```




```{r}
rs_team_lm3 <- lm(W ~ PLUS_MINUS + FGM + FTM, 
                  data=new_df)
```


```{r}
summary(rs_team_lm3)
```


```{r}
autoplot(rs_team_lm3)
```




```{r}
regular_season_dataset %>%
  select(TEAM_NAME, PLUS_MINUS, FGM, FGA, FG3M, FG3A, FTM, FTA, GP, W) %>%
  group_by(TEAM_NAME) %>%
  summarise(total_pm = sum(PLUS_MINUS),
  total_fgpct = sum(FGM)/sum(FGA),
  total_fg3pct = sum(`FG3M`)/sum(`FG3A`),
  win_pct = sum(W)/sum(GP),
  ft_pct = sum(FTM)/sum(FTA)
  ) %>%
  arrange(desc(total_pm), win_pct)
```




```{r}
rs_team_lm<- lm(`W` ~ `PLUS_MINUS`, data=regular_season_dataset)
```


```{r}
summary(rs_team_lm)
```


```{r}
plot(predict(rs_team_lm), regular_season_dataset$W,
     xlab="Predicted Wins", ylab="Actual Wins")
abline(a=0,b=1)
```





```{r}
as.binary(playoff_season_dataset$W)
```



```{r}
team_log_model <- glm(`W` ~ `team_off`, family="binomial", data=playoff_season_dataset)
```



```{r}
team_lm <- lm(`W_PCT` ~ `team_off`, data=playoff_season_dataset)
```


```{r}
summary(team_lm)
```








## Regular Season Player Clutch 2011-12 to 2021-22

```{r}
# extract all player clutch starting 2011
tc_playerdata_11 <- nba_leaguedashplayerclutch(season = "2011-12", season_type = "Regular Season")
tc_playerdata_12 <- nba_leaguedashplayerclutch(season = "2012-13", season_type = "Regular Season")
tc_playerdata_13 <- nba_leaguedashplayerclutch(season = "2013-14", season_type = "Regular Season")
tc_playerdata_14 <- nba_leaguedashplayerclutch(season = "2014-15", season_type = "Regular Season")
tc_playerdata_15 <- nba_leaguedashplayerclutch(season = "2015-16", season_type = "Regular Season")
tc_playerdata_16 <- nba_leaguedashplayerclutch(season = "2016-17", season_type = "Regular Season")
tc_playerdata_17 <- nba_leaguedashplayerclutch(season = "2017-18", season_type = "Regular Season")
tc_playerdata_18 <- nba_leaguedashplayerclutch(season = "2018-19", season_type = "Regular Season")
tc_playerdata_19 <- nba_leaguedashplayerclutch(season = "2019-20", season_type = "Regular Season")
tc_playerdata_20 <- nba_leaguedashplayerclutch(season = "2020-21", season_type = "Regular Season")
tc_playerdata_21 <- nba_leaguedashplayerclutch(season = "2021-22", season_type = "Regular Season")

# convert all extracted data into data frames and add a new column of player season
tc_playerdata_11 <- tc_playerdata_11 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2011-12")

tc_playerdata_12 <- tc_playerdata_12 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2012-13")

tc_playerdata_13 <- tc_playerdata_13 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2013-14")

tc_playerdata_14 <- tc_playerdata_14 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2014-15")

tc_playerdata_15 <- tc_playerdata_15 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2015-16")

tc_playerdata_16 <- tc_playerdata_16 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2016-17")

tc_playerdata_17 <- tc_playerdata_17 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2017-18")

tc_playerdata_18 <- tc_playerdata_18 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2018-19")

tc_playerdata_19 <- tc_playerdata_19 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2019-20")

tc_playerdata_20 <- tc_playerdata_20 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2020-21")

tc_playerdata_21 <- tc_playerdata_21 %>%
  data.frame(check.names =  FALSE) %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE)) %>%
  add_column(player_season = "2021-22")

# merge all data
nba_historical_player_clutch_list <- list(tc_playerdata_11, tc_playerdata_12, tc_playerdata_13, tc_playerdata_14, tc_playerdata_15, tc_playerdata_16, tc_playerdata_17, tc_playerdata_18, tc_playerdata_19, tc_playerdata_20, tc_playerdata_21)
nba_historical_player_clutch_data <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), nba_historical_player_clutch_list)
nba_historical_player_clutch_data$Season_Type <- "Regular Season"

```





```{r}
# read csv file extracted
team_link <- "https://raw.githubusercontent.com/moham6839/Data607_Final_Project/master/Team_Clutch_Data.csv"
nba_team_dataset <- read_csv(team_link)

head(nba_team_dataset, 1000)
```





```{r}
# calculate the team possesion and offensive effiency
nba_team_dataset <- nba_team_dataset %>%
  mutate(team_possession = 0.96*(nba_team_dataset$FGA)+(nba_team_dataset$TOV) + 0.44*(nba_team_dataset$FTA)-nba_team_dataset$OREB) %>%
  mutate(team_off = 100*(nba_team_dataset$PTS/nba_team_dataset$team_possession))

head(nba_team_dataset)
```








## Player Clutch Playoffs 2011-12 to 2021-22





```{r}
player_clutch_playoffs12 <- nba_leaguedashplayerclutch(season = "2011-12", season_type = "Playoffs")
player_clutch_playoffs12 <- data.frame(player_clutch_playoffs12, check.names = FALSE)
player_clutch_playoffs12 <- player_clutch_playoffs12 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs12$player_season <- "2011-12"


player_clutch_playoffs13 <- nba_leaguedashplayerclutch(season = "2012-13", season_type = "Playoffs")
player_clutch_playoffs13 <- data.frame(player_clutch_playoffs13, check.names = FALSE)
player_clutch_playoffs13 <- player_clutch_playoffs13 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs13$player_season <- "2012-13"


player_clutch_playoffs14 <- nba_leaguedashplayerclutch(season = "2013-14", season_type = "Playoffs")
player_clutch_playoffs14 <- data.frame(player_clutch_playoffs14, check.names = FALSE)
player_clutch_playoffs14 <- player_clutch_playoffs14 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs14$player_season <- "2013-14"


player_clutch_playoffs15 <- nba_leaguedashplayerclutch(season = "2014-15", season_type = "Playoffs")
player_clutch_playoffs15 <- data.frame(player_clutch_playoffs15, check.names = FALSE)
player_clutch_playoffs15 <- player_clutch_playoffs15 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs15$player_season <- "2014-15"


player_clutch_playoffs16 <- nba_leaguedashplayerclutch(season = "2015-16", season_type = "Playoffs")
player_clutch_playoffs16 <- data.frame(player_clutch_playoffs16, check.names = FALSE)
player_clutch_playoffs16 <- player_clutch_playoffs16 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs16$player_season <- "2015-16"


player_clutch_playoffs17 <- nba_leaguedashplayerclutch(season = "2016-17", season_type = "Playoffs")
player_clutch_playoffs17 <- data.frame(player_clutch_playoffs17, check.names = FALSE)
player_clutch_playoffs17 <- player_clutch_playoffs17 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs17$player_season <- "2016-17"


player_clutch_playoffs18 <- nba_leaguedashplayerclutch(season = "2017-18", season_type = "Playoffs")
player_clutch_playoffs18 <- data.frame(player_clutch_playoffs18, check.names = FALSE)
player_clutch_playoffs18 <- player_clutch_playoffs18 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs18$player_season <- "2017-18"


player_clutch_playoffs19 <- nba_leaguedashplayerclutch(season = "2018-19", season_type = "Playoffs")
player_clutch_playoffs19 <- data.frame(player_clutch_playoffs19, check.names = FALSE)
player_clutch_playoffs19 <- player_clutch_playoffs19 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs19$player_season <- "2018-19"


player_clutch_playoffs20 <- nba_leaguedashplayerclutch(season = "2019-20", season_type = "Playoffs")
player_clutch_playoffs20 <- data.frame(player_clutch_playoffs20, check.names = FALSE)
player_clutch_playoffs20 <- player_clutch_playoffs12 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs20$player_season <- "2019-20"


player_clutch_playoffs21 <- nba_leaguedashplayerclutch(season = "2020-21", season_type = "Playoffs")
player_clutch_playoffs21 <- data.frame(player_clutch_playoffs21, check.names = FALSE)
player_clutch_playoffs21 <- player_clutch_playoffs21 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs21$player_season <- "2020-21"


player_clutch_playoffs22 <- nba_leaguedashplayerclutch(season = "2021-22", season_type = "Playoffs")
player_clutch_playoffs22 <- data.frame(player_clutch_playoffs22, check.names = FALSE)
player_clutch_playoffs22 <- player_clutch_playoffs22 %>%
  rename_with(~ gsub("LeagueDashPlayerClutch.", "",.x, fixed=TRUE))
player_clutch_playoffs22$player_season <- "2021-22"


df_list = list(player_clutch_playoffs12, player_clutch_playoffs13, 
               player_clutch_playoffs14, player_clutch_playoffs15,
               player_clutch_playoffs16, player_clutch_playoffs17,
               player_clutch_playoffs18, player_clutch_playoffs19, 
               player_clutch_playoffs20, player_clutch_playoffs21,
               player_clutch_playoffs22)



player_new_df_list <- Reduce(
  function(x,y, ...) merge(x,y, all=TRUE, ...), df_list)
player_new_df_list$Season_Type <- "Playoffs"
player_new_df_list
```





```{r}
player_new_df_list2 <- rbind(player_new_df_list, nba_historical_player_clutch_data)
DT::datatable(player_new_df_list2)
```





```{r}
path_csv2 <- getwd()
```


```{r}
write.csv(player_new_df_list2, file.path(path_csv2, "Player_Clutch_Data.csv"))
```



